// <auto-generated />
using System;
using Challenge_Backend_Financas.Configuracoes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Challenge_Backend_Financas.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220813041849_Magration")]
    partial class Magration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Challenge_Backend_Financas.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDespesa");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("DataDespesa");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DescricaoDespesa");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("ValorDespesa");

                    b.HasKey("Id");

                    b.ToTable("TbDespesa");
                });

            modelBuilder.Entity("Challenge_Backend_Financas.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdReceita");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("DataReceita");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DescricaoReceita");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("ValorReceita");

                    b.HasKey("Id");

                    b.ToTable("TbReceita");
                });
#pragma warning restore 612, 618
        }
    }
}
